module.exports = [
  { name: '.capadobatiman', path: './assets/sounds/capadobatiman.aac' },
  { name: '.temquesefuder', path: './assets/sounds/temquesefudereacabo.mp3' },
  { name: '.tapanagostosa', path: './assets/sounds/tapanagostosa.mp3' },
  { name: '.rojaoestouradofodase', path: './assets/sounds/rojaoestouradofodase.mp3' },
  { name: '.bomdia', path: './assets/sounds/bomdia.mp3' },
  { name: '.mantega', path: './assets/sounds/mantega.mpeg' },
  { name: '.naoehnemmeiodia', path: './assets/sounds/naoehnemmeiodia.mpeg' },
  { name: '.atravessou', path: './assets/sounds/atravessou.ogg' },
  { name: '.naotatrabalhando', path: './assets/sounds/naotatrabalhando.ogg' },
  { name: '.naomedigaquarta', path: './assets/sounds/naomedigaquarta.ogg' },
  { name: '.jorjas', path: './assets/sounds/jorjas.ogg' },
  { name: '.cheirarumpo', path: './assets/sounds/cheirarumpo.ogg' },
  { name: '.famosotrescapa', path: './assets/sounds/famosotrescapa.ogg' },
  { name: '.roncojorjas', path: './assets/sounds/roncojorjas.ogg' },
  { name: '.paradeassoviarleo', path: './assets/sounds/paradeassoviarleo.ogg' },
  { name: '.lugamaopreta', path: './assets/sounds/lugamaopreta.ogg' },
  { name: '.lugabocaigualdeserto', path: './assets/sounds/lugabocaigualdeserto.ogg' },
  { name: '.lugaembonecado', path: './assets/sounds/lugaembonecado.ogg' },
  { name: '.croma', path: './assets/sounds/croma.ogg' },
  { name: '.lukerojustin', path: './assets/sounds/lukerojustin.ogg' },
  { name: '.churrasjorjas', path: './assets/sounds/churrasjorjas.ogg' },
  { name: '.pampalavada', path: './assets/sounds/pampalavada.ogg' },
  { name: '.mauroxluga', path: './assets/sounds/mauroxluga.ogg' },
  { name: '.euvouurva', path: './assets/sounds/euvouurva.ogg' },
  { name: '.acordeiestressado', path: './assets/sounds/acordeiestressado.ogg' }
];
